import {
  advanceDateByFrequency,
  calculateLineTotal,
  calculateTotals,
  type ContractFrequency,
} from "@/lib/finance/utils";
import type { PdfDocumentData, PdfLineItem } from "@/lib/finance/pdf";
import type { InvoiceListRow } from "@/lib/finance/invoices-data";

export type InvoiceKind = "one_time" | "recurring";

export type InvoiceEventType =
  | "created"
  | "updated"
  | "sent"
  | "paid"
  | "partial"
  | "overdue"
  | "cancelled"
  | "duplicated"
  | "deleted"
  | "payment_received"
  | "pdf_generated"
  | "recurring_generated";

export interface ContractInvoiceItem {
  description: string;
  quantity: number;
  unit_price_cents: number;
  line_total_cents: number;
  sort_order?: number;
}

export interface ContractForInvoice {
  id: string;
  title: string;
  service_description: string | null;
  amount_cents: number;
  frequency: string;
  tax_rate: number;
  discount_cents?: number | null;
  subtotal_cents?: number | null;
  tax_cents?: number | null;
  total_cents?: number | null;
  end_date: string | null;
  next_invoice_date: string | null;
  notes?: string | null;
  bank_details?: string | null;
  client_name?: string | null;
  client_company?: string | null;
  client_email?: string | null;
  client_phone?: string | null;
  items?: ContractInvoiceItem[];
}

export interface ClientForInvoice {
  name: string;
  contact_name?: string | null;
  email?: string | null;
  phone?: string | null;
}

export interface GeneratedInvoiceDraft {
  kind: InvoiceKind;
  periodStart: string | null;
  periodEnd: string | null;
  issueDate: string;
  dueDate: string;
  clientName: string;
  clientCompany: string | null;
  clientEmail: string | null;
  clientPhone: string | null;
  taxRate: number;
  discountCents: number;
  notes: string | null;
  bankDetails: string | null;
  autoGenerated: boolean;
  subtotalCents: number;
  taxCents: number;
  totalCents: number;
  lineItems: Array<{
    description: string;
    quantity: number;
    unitPriceCents: number;
    lineTotalCents: number;
  }>;
}

const DEFAULT_DUE_DAYS = 14;

export function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export function periodEndForContract(
  periodStart: string,
  frequency: ContractFrequency,
  contractEnd: string | null,
): string {
  const start = new Date(periodStart);
  const next = advanceDateByFrequency(start, frequency);
  next.setDate(next.getDate() - 1);
  const endStr = next.toISOString().slice(0, 10);
  if (contractEnd && endStr > contractEnd) return contractEnd;
  return endStr;
}

export function contractLineItems(contract: ContractForInvoice): PdfLineItem[] {
  if (contract.items && contract.items.length > 0) {
    return contract.items.map((item) => ({
      description: item.description,
      quantity: Number(item.quantity),
      unitPriceCents: item.unit_price_cents,
      lineTotalCents: item.line_total_cents,
    }));
  }

  return [
    {
      description: contract.service_description ?? contract.title,
      quantity: 1,
      unitPriceCents: contract.amount_cents,
      lineTotalCents: contract.amount_cents,
    },
  ];
}

export function buildInvoiceFromContract(
  contract: ContractForInvoice,
  client: ClientForInvoice,
  options: {
    mode: "recurring" | "one_time";
    periodStart?: string | null;
    issueDate?: string;
    dueDays?: number;
  },
): GeneratedInvoiceDraft {
  const today = new Date().toISOString().slice(0, 10);
  const issueDate = options.issueDate ?? today;
  const isRecurring = options.mode === "recurring";
  const periodStart =
    isRecurring && options.periodStart
      ? options.periodStart
      : isRecurring
        ? contract.next_invoice_date
        : null;

  const periodEnd =
    periodStart && isRecurring
      ? periodEndForContract(
          periodStart,
          contract.frequency as ContractFrequency,
          contract.end_date,
        )
      : null;

  const lineItems = contractLineItems(contract).map((item) => ({
    description: item.description,
    quantity: item.quantity,
    unitPriceCents: item.unitPriceCents,
    lineTotalCents: item.lineTotalCents,
  }));

  const totals = calculateTotals(
    lineItems.map((item) => ({ lineTotalCents: item.lineTotalCents })),
    Number(contract.tax_rate),
    contract.discount_cents ?? 0,
  );

  return {
    kind: isRecurring ? "recurring" : "one_time",
    periodStart,
    periodEnd,
    issueDate,
    dueDate: addDays(issueDate, options.dueDays ?? DEFAULT_DUE_DAYS),
    clientName: contract.client_name ?? client.name,
    clientCompany: contract.client_company ?? client.contact_name ?? null,
    clientEmail: contract.client_email ?? client.email ?? null,
    clientPhone: contract.client_phone ?? client.phone ?? null,
    taxRate: totals.taxRate,
    discountCents: contract.discount_cents ?? 0,
    notes: contract.notes ?? null,
    bankDetails: contract.bank_details ?? null,
    autoGenerated: isRecurring,
    subtotalCents: totals.subtotalCents,
    taxCents: totals.taxCents,
    totalCents: totals.totalCents,
    lineItems,
  };
}

export function invoiceKindLabel(kind: InvoiceKind | string | null | undefined): InvoiceKind {
  return kind === "recurring" ? "recurring" : "one_time";
}

export function invoiceToPdfDocument(
  invoice: InvoiceListRow,
  company: PdfDocumentData["company"],
  locale: string,
  labels: PdfDocumentData["labels"],
): PdfDocumentData {
  const items: PdfLineItem[] = (invoice.items ?? []).map((item) => ({
    description: item.description,
    quantity: Number(item.quantity),
    unitPriceCents: item.unit_price_cents,
    lineTotalCents: item.line_total_cents,
  }));

  return {
    type: "invoice",
    number: invoice.invoice_number,
    company,
    clientName: invoice.client_name,
    clientCompany: invoice.client_company,
    clientEmail: invoice.client_email,
    clientPhone: null,
    issueDate: invoice.issue_date,
    dueDate: invoice.due_date,
    items,
    subtotalCents: invoice.subtotal_cents,
    taxRate: Number(invoice.tax_rate),
    taxCents: invoice.tax_cents,
    totalCents: invoice.total_cents,
    notes: invoice.notes,
    bankDetails: invoice.bank_details,
    locale,
    labels,
  };
}

export function recalculateLineItem(
  quantity: number,
  unitPriceCents: number,
  discountPercent = 0,
) {
  return calculateLineTotal(quantity, unitPriceCents, discountPercent);
}
