import type { SupabaseClient } from "@supabase/supabase-js";
import { generateServiceReport } from "@/lib/field-execution/generate-service-report";
import { createAdminClient } from "@/lib/supabase/admin";

async function notifySupervisors(
  companyId: string,
  type: string,
  title: string,
  body: string,
  entityType?: string,
  entityId?: string,
) {
  const admin = createAdminClient();
  const { data: members } = await admin
    .from("company_members")
    .select("user_id")
    .eq("company_id", companyId)
    .in("role", ["admin", "supervisor"])
    .eq("status", "active");

  if (!members?.length) return;

  await admin.from("notifications").insert(
    members.map((m) => ({
      company_id: companyId,
      recipient_id: m.user_id,
      type,
      title,
      body,
      entity_type: entityType ?? null,
      entity_id: entityId ?? null,
    })),
  );
}

export async function generateReportForTask(
  supabase: SupabaseClient,
  companyId: string,
  taskId: string,
  taskTitle?: string,
): Promise<{ reportId?: string; storagePath?: string }> {
  const { data: checkIn } = await supabase
    .from("check_ins")
    .select("id")
    .eq("task_id", taskId)
    .eq("company_id", companyId)
    .not("check_out_at", "is", null)
    .order("check_out_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (checkIn?.id) {
    const result = await generateServiceReport(
      companyId,
      taskId,
      checkIn.id,
      supabase,
    );
    if (result) {
      const { data: task } = await supabase
        .from("tasks")
        .select("title, scheduled_date, address:addresses(client_id)")
        .eq("id", taskId)
        .eq("company_id", companyId)
        .single();

      const address = task?.address
        ? Array.isArray(task.address)
          ? task.address[0]
          : task.address
        : null;
      const clientId = (address as { client_id?: string } | null)?.client_id ?? null;

      await supabase.from("reports").insert({
        company_id: companyId,
        report_type: "client",
        title: `Relatório de serviço — ${task?.title ?? taskTitle ?? taskId}`,
        period_start: task?.scheduled_date ?? null,
        period_end: task?.scheduled_date ?? null,
        storage_path: result.storagePath,
        client_id: clientId,
        visible_to_client: true,
        metadata: {
          taskId,
          serviceReportId: result.reportId,
          autoGenerated: true,
        },
      });

      return result;
    }
  }

  const { data: task } = await supabase
    .from("tasks")
    .select("title, scheduled_date, address:addresses(client_id)")
    .eq("id", taskId)
    .eq("company_id", companyId)
    .single();

  const address = task?.address
    ? Array.isArray(task.address)
      ? task.address[0]
      : task.address
    : null;
  const clientId = (address as { client_id?: string } | null)?.client_id ?? null;

  await supabase.from("reports").insert({
    company_id: companyId,
    report_type: "client",
    title: `Relatório pendente — ${task?.title ?? taskTitle ?? taskId}`,
    period_start: task?.scheduled_date ?? null,
    period_end: task?.scheduled_date ?? null,
    client_id: clientId,
    visible_to_client: false,
    metadata: { taskId, autoGenerated: true, pendingExecution: true },
  });

  await notifySupervisors(
    companyId,
    "automation_report",
    "Relatório de serviço pendente",
    task?.title
      ? `Conclua a execução de campo para gerar o PDF: ${task.title}`
      : "Automação registou relatório pendente",
    "task",
    taskId,
  );

  return {};
}
